version: "3.9"
services:
  backend:
    build:
      context: ./backend
    env_file:
      - shared.env
    depends_on:
      - database

  database:
    build:
      context: ./database
    restart: always
    env_file:
      - shared.env
